export const characters = [
    {
        name:"Django",
        image:"boss_rat.png"
    },
    {
        name:"Raphael",
        image:"ninja.png"
    },
    {
        name:"Razmo",
        image:"razmo.png"
    },
    {
        name:"angry_shrek",
        image:"angry_shrek.png"
    },
    {
        name:"shrek_run",
        image:"shrek_run.png"
    },
    {
        name:"shrek_tpose",
        image:"shrek_tpose.png"
    },
]